allowBuilds:
  cbor-extract: false
  esbuild: false
engineStrict: true

packages:
  - "packages/*"
  - "packages/core/examples/*"

patchedDependencies:
  '@automerge/automerge-repo': patches/@automerge__automerge-repo.patch
  '@automerge/automerge-repo-keyhive': patches/@automerge__automerge-repo-keyhive.patch

catalog:
  "@automerge/automerge": 3.4.1
  "@automerge/automerge-repo": 2.6.0-subduction.48
  "@automerge/automerge-repo-keyhive": 0.5.0-alpha.6
  "@automerge/automerge-repo-storage-indexeddb": 2.6.0-subduction.48
  "@automerge/automerge-repo-storage-nodefs": 2.6.0-subduction.48
  "@automerge/automerge-subduction": 0.16.1
  "@automerge/keyhive-react": 0.1.0-alpha.3
  "@automerge/react": 2.6.0-subduction.48
  "@keyhive/keyhive": 0.1.0-alpha.8

overrides:
  "@automerge/automerge-repo": "catalog:"
  "@automerge/automerge-subduction": "catalog:"
