packages:
  - "packages/*"
  - "packages/core/examples/*"
patchedDependencies:
  '@automerge/automerge-repo': patches/@automerge__automerge-repo.patch
  '@automerge/automerge-repo-keyhive': patches/@automerge__automerge-repo-keyhive.patch
